sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx
  
haxe:
  - "3.2.1"
  - development
  
matrix:
  allow_failures:
    - haxe: development
    
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install mongodb;
      sudo mkdir -p /data/db;
      sudo mongod &
    else
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927;
      echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list;
      sudo apt-get update;
      sudo apt-get install -y mongodb-org;
    fi
    
install:
  - haxelib install travix
  - haxelib run travix install
  - haxelib git bson https://github.com/kevinresol/bson
  - haxelib git tink_tcp https://github.com/haxetink/tink_tcp
  - haxelib git tink_io https://github.com/haxetink/tink_io
  - haxelib git tink_streams https://github.com/haxetink/tink_streams

script:
  - haxelib run travix node
